sudo: false
language: node_js
node_js:
- '4'
deploy:
  provider: npm
  api_key: "jo5dLOPdNyxEnBupgZbJ3qDLU3IDcAeVzsUf4CxrO8TGfJF+US2UyG5Z4gZn5f4o78ErhWDRkkKUQ7lckm/eyKOrqqWCZrxh9toIhhdLAfGdyYTADZHS5QNcfV+wqTXOCE2VNDbShzsKcNM4jeU087R4Pb0DKNRw0Z1R1gTSiL4/REk1O16PcKJ/OlP3EiGk719ohhxULWi0pvIP5MXbhMiE736te1jO7OhsSZRdwH2JvWCpcyhJ/lt4PL3/g7i1iDmffnS5/9yI3GoPzKVPgnCv01+3s455ln2GVAJ+acogqHjLrWWyqpXZ+jIYTjqIJyb/WLfUtaTQip/4pXrUcKqqgMUChrSvJJbLjBU5XemtKIsPgphXTAMqSqWrfpNQ3L/5ZxiF5MIP8ACAyEyaekpjSO/xOp9gK6yfRvu26ujKI4CRsbbDwzal7Q+XaKsqoIrAFw436D9hm/88LcURuiNCe1OJYRstVdPpr0nsWN8QCAGrRpzGYyUw/6DiAxrvSSnraXfU5tChp6Nuy7q/KWQ9YoX1nVbfj6ysNvOYWsNP1sp32e8+7sMXgr4Y4XV0VzoqvxLu5l2nK3i01+sy+DHtD2YCuBny9v8zHh9IcAF4mVdpt4LrGY/7T5YkpkJQvQ7nywUujYrZI7Iu1Vp8KabGBH9a25SvyII8gZOgTXQ="